### ISSUE TITLE
APP

### ISSUE THREAD

**Issue by sylviechambon** [tforgione/adejs#8]
Coucou Thomas ! 
Tous les trucs notés APP ne comptent pas alors qu'ils devraient ;) 
Merci ! 
Sylvie.

**Comment by tforgione** [comment]
Salut,

effectivement, y'a une partie des cours APP qui ont gardé le nom du cours qu'il y aurait eu à la place (auquel cas, le truc marche normalement si je dis pas de bétises).

Je vois que ceux qui sont notés juste *APP* sont de la même couleur que les cours magistraux. Ça veut dire qu'ils comptent autant qu'un cours magistral ? Tous ?
